In [1]:
import numpy as np


In [3]:
np.__version__

'1.19.3'

In [4]:
np.__path__

['c:\\users\\aarun\\m1_mor\\lib\\site-packages\\numpy']

In [6]:
list1 = [1,2,3,4]

In [7]:
list2 = [4,5,6,7]

In [8]:
list2d = [[1,2],[3,4]]

In [11]:
print(list2d)

[[1, 2], [3, 4]]


In [12]:
arr1 = np.array(list2d)

In [13]:
arr1


array([[1, 2],
       [3, 4]])

In [14]:
list2d2 = [[4,5],[6,7]]

In [15]:
arr2 = np.array(list2d2)

In [16]:
arr2

array([[4, 5],
       [6, 7]])

In [17]:
arr1-arr2

array([[-3, -3],
       [-3, -3]])

In [18]:
arr1.shape


(2, 2)

In [20]:
arr1.dtype

dtype('int32')

In [30]:
list3 = ['arunrimalarun',30,1.1]

In [31]:
x=np.array(list3)

In [32]:
x

array(['arunrimalarun', '30', '1.1'], dtype='<U13')

In [33]:
x.dtype   #string > float > int > boolean

dtype('<U13')

### arange

In [5]:
import numpy as np
arr1 = np.arange(0,16,1)

In [6]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### hstack & vstack

In [7]:
list2d = [[1,2],[3,4]]

In [8]:
list2d_2 = [[1,2],[3,4]]

In [9]:
arr1 = np.array(list2d)

In [10]:
arr2 = np.array(list2d_2)

In [12]:
np.hstack((arr1,arr2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [13]:
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

### linspace

In [17]:
arr1 = np.linspace(1,10,4)   
# ((10+1)/4) generate 4 numbers evenly spaced from 1 to 10

In [15]:
arr1

array([ 1.,  4.,  7., 10.])

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr1 = np.linspace(1,10,4, endpoint=False)
# doesn't include 10

In [21]:
arr1

array([1.  , 3.25, 5.5 , 7.75])

### astype

In [33]:
arr3=arr1.astype(int)

In [34]:
arr3.dtype

dtype('int32')

In [62]:
arr1 = np.array([1,2,3,5,7,127])

In [63]:
arr2 = arr1.astype('uint8')  # 2^7-1 (_sign) (_ _ _number 2^7-1 _ _ _ _)

In [64]:
arr2.dtype

dtype('uint8')

In [65]:
arr2

array([  1,   2,   3,   5,   7, 127], dtype=uint8)

### diagonal

In [66]:
np.diag([1,2])  # diagonal element are 1 & 2 

array([[1, 0],
       [0, 2]])

In [67]:
 np.diag([1,2,3] , k=-1) 
 # diagonal element will shift downward by 1 place below the main diagonal 
 # similarly when k=1 , diagonal elements shift toward right from the main 
 # diagonal by 1 palce

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [72]:
np.diag([1,2,3] , k=4)

array([[0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [69]:
arr1 = np.array([[1,2],[3,4]])

In [70]:
arr1

array([[1, 2],
       [3, 4]])

In [71]:
np.diag(arr1)

array([1, 4])

### reshape & flatten

In [73]:
arr1 = np.array([[1,2],[3,4],[5,6]])

In [75]:
arr1.shape

(3, 2)

In [76]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
arr1.reshape(2,3) # to reshape array 

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
arr1.flatten()

array([1, 2, 3, 4, 5, 6])

In [82]:
(arr1.flatten()).shape  # one row with 6 elements

(6,)

### 3D array

In [85]:
arr_3d = np.array([  [[1,2],[3,4]] , [[4,5],[6,7]]   ])

In [86]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [87]:
arr_3d.shape  # 2 arrays of 2 by 2 array

(2, 2, 2)

In [88]:
arr_3d = np.array([  [[1,2],[3,4]] , [[4,5],[6,7]] , [[8,9],[0,1]]  ])

In [92]:
arr_3d   # 3 arrays of 2 by 2 array

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]],

       [[8, 9],
        [0, 1]]])

In [91]:
arr_3d.shape  # 3 arrays of 2 by 2 array

(3, 2, 2)

### index & slice

In [94]:
arr1 = np.array([[1,2],[3,4],[5,6]])

In [95]:
arr1 = np.array([1,2,3])

In [96]:
arr1[0:2]

array([1, 2])

In [98]:
arr2 = np.array([[1,2],[3,4],[5,6]])

In [99]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [101]:
arr2[2]  # return corresponding row , here 2nd row. row , column starts from 0

array([5, 6])

In [102]:
arr2[2,1]

6

In [103]:
arr2[0:2,0]

array([1, 3])

In [104]:
arr2[0:2,1]

array([2, 4])

In [105]:
arr2[0:2,1:]

array([[2],
       [4]])

In [107]:
arr3 = np.array([[1,2,5],[3,4,7],[5,6,9]])

In [108]:
arr3

array([[1, 2, 5],
       [3, 4, 7],
       [5, 6, 9]])

In [109]:
arr3[1:,1:]

array([[4, 7],
       [6, 9]])

### Statistic

In [111]:
arr3.min()

1

In [112]:
arr2.max()

9

In [113]:
arr2.min()

1

In [114]:
arr2.std()

2.3570226039551585

In [117]:
np.median(arr2)

5.0